=== cu-clear/RussianPropbank/Frames/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>
<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>
<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*

  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
<!ELEMENT roleset (aliases?, note*, mappings*, note*, roles, ( example | note )*)>
<!ATTLIST roleset
  id   CDATA #REQUIRED
  name CDATA #REQUIRED
  usage CDATA #IMPLIED>
<!ELEMENT aliases (alias*, mwe*)>
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
pos (v | n | j | l | m | x | p) #REQUIRED
verbnet CDATA #REQUIRED
framenet CDATA #REQUIRED
usage CDATA #IMPLIED>
<!ELEMENT mwe (token*)>
<!ATTLIST mwe id CDATA #REQUIRED>
<!ELEMENT token (#PCDATA)>
<!ATTLIST token
slot (A | B | C | D | E | F | G | H | I | J | K | L | M) #REQUIRED
head CDATA #IMPLIED
dep CDATA #IMPLIED
pos CDATA #IMPLIED
arg CDATA #IMPLIED>


<!ELEMENT mappings (source, target)>
<!ATTLIST mappings alias CDATA #REQUIRED>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT roles   (note | role)*>
<!ELEMENT role (vnrole | fnrole)* >
<!--
  roles have a number (or an "M" associated
  with them, for common adjuncts that don't qualify for number argument status). 
  Both numbered arguments and adjuncts are labeled with the function tags from the list below:

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose
    PNC  purpose no cause (no longer used)
    CAU  cause
    CXN  constructional pattern (adjectival comparative marker)
    ADJ  adjectival (nouns only)
    COM  comitative
    DIS  discourse
    DSP  direct speech
    GOL  goal
    PAG  prototypical agent (function tag for arg1)
    PPT  prototypical patient (function tag for arg1)
    RCL  relative clause (no longer used)
    SLC  selectional constraint link
    VSP  verb specific (function tag for numbered arguments)
    LVB  light verb (for nouns only)

-->
<!ATTLIST role
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | m | M ) #REQUIRED
  f ( PAG | PPT | GOL | CXN | VSP | COM | ADJ | CAU | PRP | MNR | EXT | LOC | DIR | ADV | TMP | adv | tmp | pag | ppt | gol | vsp | com | adj | cau | prp | rec | mnr | ext | loc | dir | prd | PRD ) #REQUIRED
  descr CDATA #REQUIRED>
<!ELEMENT vnrole EMPTY>
<!ATTLIST vnrole
  vncls CDATA #REQUIRED
  vntheta (actor| Actor| actor1| Actor1 |actor2|  Actor2| agent| Agent|
  asset| Asset| attribute| Attribute| beneficiary| Beneficiary| cause| Cause|
  causer| Causer| co-agent | Co-Agent | co-patient | Co-Patient | co-theme | Co-Theme | 
  destination| Destination| experiencer| Experiencer| extent| Extent| 
  goal | Goal | initial_location | Initial_Location |
  instrument| Instrument| location| Location| material| Material| patient|
  Patient| patient1| Patient1| patient2| Patient2| pivot | Pivot | 
  predicate| Predicate| product| Product| recipient| Recipient| reflexive | Reflexive | result | Result |
  source| Source| stimulus| Stimulus| theme| Theme|theme1| Theme1| theme2| Theme2| time| Time| topic|
  Topic| Trajectory | trajectory | proposition| Proposition| value| Value | unspecified) #REQUIRED>
<!ELEMENT fnrole EMPTY>
<!ATTLIST fnrole
frame CDATA #REQUIRED
fe CDATA #REQUIRED>
<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->
<!ELEMENT example (inflection?, note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  type CDATA #IMPLIED
  src  CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>
<!ELEMENT inflection EMPTY>
<!ATTLIST inflection
  person (third | other | ns) "ns"
  tense  (present | past | future | ns) "ns"
  aspect (perfect | progressive | both | ns) "ns"
  voice  (active | passive | ns) "ns"
  form   (infinitive | gerund | participle | full | ns) "ns">
<!-- the n and f attributes corresponds to those of the roles
     described above -->
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | m | M | a | A) #REQUIRED
  f CDATA #IMPLIED>
<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  f CDATA #IMPLIED>

=== cu-clear/RussianPropbank/Frames/бушевать-rage.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
    <predicate lemma="бушевать">
        <roleset id="бушевать.01" name="Rage, storm, billow.">
            <aliases>
                <alias pos="v">бушевать</alias>
                <alias pos="j">бушующий</alias>
            </aliases>
            <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
            <note>NOTES: based on English billow.01</note>
            <roles>
                <role descr="Entity storming" f="PPT" n="1"/>
                <role descr="Location or Direction" f="LOC" n="2"/>
            </roles>
            <lexlinks>
                <lexlink class="billow.01" resource="English PropBank" version="3.4"/>
            </lexlinks>
            <example name="ARG1 and ARG2" src="south-sudan.ru (Russian Web 2010)">
                <text>Судан страдает от гражданских войн , которые бушуют на его территории , на протяжении более 40 лет
                    .
                </text>
                <propbank>
                    <arg type="ARG1" start="3" end="4">гражданских войн</arg>
                    <rel relloc="7">бушуют</rel>
                    <arg type="ARG2" start="8" end="10">на его территории</arg>
                </propbank>
            </example>
            <example name="ARG1 only" src="kp.ru (Russian Web 2010)">
                <text>До конца недели будет бушевать мощная магнитная буря .</text>
                <propbank>
                    <arg type="ARG1" start="5" end="7">мощная магнитная буря</arg>
                    <rel relloc="4">бушевать</rel>
                </propbank>
            </example>
        </roleset>
    </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/планировать-plan.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="Планировать">
    <roleset id="планировать.01" name="Plan, schedule, map out">
      <aliases>
        <alias pos="v">планировать</alias>
        <alias pos="v">спланировать</alias>
        <alias pos="v">распланировать</alias>
        <alias pos="j">планирующий</alias>
        <alias pos="j">спланированный</alias>
	    </aliases>
	    <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
	    <note>NOTES: based on English plan.01</note>

      <roles>
        <role descr="Planner" f="PAG" n="0"/>
        <role descr="Thing planned" f="PPT" n="1"/>
	    </roles>

      <example name="Arg0 and Arg1" src="RNC, Борис Можаев. Саня (1957)">
        <text>― Я уже все распланировал : тут будет у нас спальня , здесь вроде гостиной .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">Я</arg>
          <rel relloc="?">распланировал</rel>
	        <arg type="ARG1" start="?" end="?">все</arg>
        </propbank>
      </example>

      <example name="Arg0 and Arg1" src="_">
        <text>Комиссия планирует провести беседу на следующей недели .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">Комиссия</arg>
          <rel relloc="?">планирует</rel>
	        <arg type="ARG1" start="?" end="?">провести беседу на следующей недели</arg>
        </propbank>
      </example>
	  </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/прекратиться-cease.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
	<predicate lemma="прекратиться">
	<note>NOTES: Added for LORELEI to support aligning RU and EN texts. Data from Skatje Myers.</note>
		<roleset id="прекратиться.01" name="cease">
			<aliases>
				<alias framenet="" pos="j" verbnet="">прекратившийся</alias>
				<alias framenet="" pos="v" verbnet="">прекращаться</alias>
				<alias framenet="" pos="j" verbnet="">прекращающийся</alias>
				<alias framenet="" pos="j" verbnet="">прекращавшийся</alias>
				<alias framenet="" pos="j" verbnet="">прекращать</alias>
				<alias framenet="" pos="j" verbnet="">прекращающий</alias>
				<alias framenet="" pos="j" verbnet="">прекращавший</alias>
				<alias framenet="" pos="j" verbnet="">прекращаемый</alias>
				<alias framenet="" pos="v" verbnet="">прекратить</alias>
				<alias framenet="" pos="j" verbnet="">прекративший</alias>
				<alias framenet="" pos="j" verbnet="">прекращённый</alias>
				<alias framenet="" pos="j" verbnet="">прекращенный</alias>
			</aliases>
			<note>Corresponds to FrameBank senses 1</note>
			<note>прекратиться.01 NOTES: Frame based on adjustment of English cease.01</note>
			<roles>
				<role descr="causer of ceasing, Agent" f="pag" n="0" />
				<role descr="Theme (action or object being stopped)" f="ppt" n="1" />
			</roles>
			<example name="arg1 only" src="" type="">
				<text>В субботу осадки прекратились , выглянуло солнце и движение в столице возобновилось .</text>
				<arg f="tmp" n="m">В субботу</arg>
				<arg f="" n="1">осадки</arg>
				<rel f="">прекратились</rel>
			</example>
			<example name="active imperfective" src="Л. Н. Толстой, «Война и мир», 1867—1869 г. (цитата из Национального корпуса русского языка, см. Список литературы)" type="">
				<text>Несмотря на свою рассеянность и добродушие , личность Пьера прекращала тотчас же всякие попытки на насмешку в его присутствии . </text>
				<arg f="adv" n="m">Несмотря на свою рассеянность и добродушие</arg>
				<arg f="" n="0">личность Пьера</arg>
				<rel f="">прекращала</rel>
				<arg f="tmp" n="m">тотчас же</arg>
				<arg f="" n="1">всякие попытки на насмешку в его присутствии</arg>
			</example>
			<example name="active perfective" src="Russian National Corpus" type="">
				<text>В тот же день ЦБ прекратил деятельность временной администрации Москомприватбанка</text>
				<arg f="tmp" n="m">В тот же день</arg>
				<arg f="" n="0">ЦБ</arg>
				<rel f="">прекратил</rel>
				<arg f="" n="1">деятельность временной администрации Москомприватбанка</arg>
			</example>
		</roleset>
	</predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/закрывать-close.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="закрывать">
    <roleset id="закрывать.01" name="close, shut, cover">
      <aliases>
        <alias framenet="" pos="v" verbnet="">закрывать</alias>
        <alias framenet="" pos="v" verbnet="">закрыть</alias>
        <alias framenet="" pos="j" verbnet="">закрывающий</alias>
        <alias framenet="" pos="j" verbnet="">закрывавший</alias>
        <alias framenet="" pos="j" verbnet="">закрывший</alias>
	  </aliases>
	  <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
	  <note>NOTES: based on English close.01</note>
      <roles>
        <role descr="person doing the closing" f="PAG" n="0"/>
        <role descr="thing closing" f="PPT" n="1"/>
        <role descr="anti-beneficiary" f="GOL" n="2"/>
	  </roles>
      <example name="ARG0 and 1" src="RNC, http://murzilka.km.ru/ «Мурзилка», 2003, № 1-5" type="">
        <text>Эле-Фантик закрыл глаза и сразу понял, что мысль проросла на славу .</text>
        <arg f="" n="0">Эле-Фантик</arg>
        <rel f="">закрыл</rel>
	      <arg f="" n="1">глаза</arg>
      </example>
      <example name="ARG0, 1, and 2" src="RNS, Сати Спивакова. Не всё. «Вагриус», 2002" type="">
        <text>Просто он закрыл для себя тему Максима Венгерова.</text>
        <arg f="" n="0">он</arg>
        <rel f="">закрыл</rel>
	      <arg f="" n="2">себя</arg>
        <arg f="" n="1">тему</arg>
      </example>
      <example name="ARG0, 1, and 2" src="RNS, 	«Известия», 19.06.2002" type="">
        <text>В Турции всё смешалось: полиция от греха подальше закрыла улицы для автотранспорта ...</text>
        <arg f="" n="0">полиция</arg>
        <rel f="">закрыла</rel>
        <arg f="" n="1">улицы</arg>
	      <arg f="" n="2">автотранспортая</arg>
      </example>
	</roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/произойти-happen.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="произойти">
  <note>NOTES: Added for LORELEI to support aligning RU and EN texts. Data from Skatje Myers.</note>
	<roleset id="произойти.01" name="happen">
	  <aliases>
		<alias framenet="" pos="j" verbnet="">произошедший</alias>
		<alias framenet="" pos="j" verbnet="">происшедший</alias>
		<alias framenet="" pos="v" verbnet="">происходить</alias>
		<alias framenet="" pos="j" verbnet="">происходящий</alias>
		<alias framenet="" pos="j" verbnet="">происходивший</alias>
	  </aliases>
	  <note>Corresponds to FrameBank sense 2</note>
	  <note>произойти.01 NOTES: Based on happen.01.</note>
	  <roles>
		<role descr="event" f="PPT" n="1"/>
		<role descr="benefactive" f="GOL" n="2"/>
	  </roles>
	  <example name="happen, occur" src="" type="">
		<text>Произошла авария</text>
		<rel f="">Произошла</rel>
		<arg f="" n="1">авария</arg>
	  </example>
	  <example name="predicate adjective, occur" src="Russian National Corpus" type="">
		<text>16октября ФА объявила, что будет расследовать инцидент, происшедший между Эвра иСуаресом.</text>
		<arg f="" n="1">инцидент</arg>
		<rel f="">происшедший</rel>
		<arg f="" n="2">между Эвра иСуаресом</arg>
	  </example>
	</roleset>

	<roleset id="произойти.02" name="originate">
	  <aliases>
		<alias framenet="" pos="j" verbnet="">произошедший</alias>
	  </aliases>
	  <note>Corresponds to FrameBank senses 1</note>
	  <note>произойти.02 NOTES: Based on descend.01.</note>
	  <roles>
	   <role descr="entity descended" f="PPT" n="1"/>
		<role descr="source, ancestor" f="DIR" n="2"/>
	  </roles>
	  <example name="descend, originate" src="" type="">
		<text>Мужчины произошли от других обезьян .</text>
		<arg f="" n="1">Мужчины</arg>
		<rel f="">произошли</rel>
		<arg f="" n="2">от других обезьян</arg>
	  </example>
	  <example name="originate, imperfective" src="Л. Н. Толстой, «Богу или Маммоне?», 1896 г. (цитата из Национального корпуса русского языка, см. Список литературы)" type="">
		<text>То же , что веселье , которое происходит от вина , не есть настоящее и не радостное веселье , не нужно и доказывать .</text>
		<arg f="" n="1">которое</arg>
		<rel f="">происходит</rel>
		<arg f="" n="2">от вина</arg>
	  </example>
	  <example name="descend, birthed" src="Russian National Corpus" type="">
		<text>С тех пор, как мне впервые улыбнулся произошедший от меня младенец, я знаю, что любить можно иное и иначе.</text>
		<rel f="">произошедший</rel>
		<arg f="" n="2">от меня</arg>
		<arg f="" n="1">младенец</arg>
	  </example>
	</roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/стоить-cost.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="стоить">
    <note>NOTES: Added for LORELEI to support aligning RU and EN texts. Data from Skatje Myers.</note>
    <roleset id="стоить.01" name="cost">
      <aliases>
        <alias pos="j">стоящий</alias>
        <alias pos="j">стоивший</alias>
        <alias pos="v">стоивши</alias>
        <alias pos="v">стоив</alias>
      </aliases>
      <note>Corresponds to FrameBank senses 1,2</note>
      <note>стоить.01 NOTES: Based on cost.01</note>
      <roles>
        <role descr="commodity" f="PPT" n="1"/>
        <role descr="price" f="vsp" n="2"/>
      </roles>
      <example name="cost" src="">
        <text>Фигово ей ) Щетка стоит примерно 4 тысячи , если она реально лучше обычной , то обязательно возьму . Лучше предотвратить кариес , чем лечить его</text>
        <propbank>
          <arg type="ARG1" start="3" end="3">Щетка</arg>
          <rel relloc="4">стоит</rel>
          <arg type="ARGM-ADV" start="5" end="5">примерно</arg>
          <arg type="ARG2" start="6" end="7">4 тысячи</arg>
        </propbank>
      </example>
    </roleset>
    <roleset id="стоить.02" name="be worth">
      <aliases>
        <alias pos="j">стоящий</alias>
        <alias pos="j">стоивший</alias>
        <alias pos="v">стоивши</alias>
        <alias pos="v">стоив</alias>
      </aliases>
      <note>Corresponds to FrameBank senses 3,4,5</note>
      <note>стоить.02 NOTES: Based on worth.01</note>
      <roles>
        <role descr="worthy thing" f="PAG" n="1"/>
        <role descr="worthy of what" f="PPT" n="2"/>
        <role descr="entity recognizing value" f="GOL" n="3"/>
      </roles>
      <example name="worth it" src="">
        <text>Но разве оно того стоило ?</text>
        <propbank>
          <arg type="ARGM-DIS" start="0" end="0">Но</arg>
          <arg type="ARGM-ADV" start="1" end="1">разве</arg>
          <arg type="ARG1" start="2" end="2">оно</arg>
          <arg type="ARG2" start="3" end="3">того</arg>
          <rel relloc="4">стоило</rel>
        </propbank>
      </example>
      <example name="should, worth doing" src="">
        <text>Погорельцам стоит пикет организовать , причем реальный с лопатами и вилами , для тупорылых ментов можно огонь прихватить и еще дома сжечь местных чиновников , чтоб в следующий раз мозгами думали а не жопой и делать это нужно всем вместе .</text>
        <propbank>
          <arg type="ARG3" start="0" end="0">Погорельцам</arg>
          <rel relloc="1">стоит</rel>
          <arg type="ARG2" start="2" end="3">пикет организовать</arg>
        </propbank>
      </example>
    </roleset>
    <roleset id="стоить.03" name="all it takes, barely begin, just do it">
      <aliases>
	  </aliases>
      <note>Corresponds to FrameBank sense 6</note>
      <note>стоить.03 NOTES: Based on English begin.02</note>
      <note>Often followed by word "только", "лишь", "всего лишь", etc.</note>
      <roles>
        <role descr="Action (barely) begun" f="PPT" n="1"/>
        <role descr="Instrument, starting point" f="MNR" n="2"/>
      </roles>
      <example name="only begin" src="М. А. Булгаков, «Мастер и Маргарита, часть 1», 1929-1940 г. (цитата из Национального корпуса русского языка, см. Список литературы)">
        <text>Ну , а колдовству , как известно , стоит только начаться , а там уж его ничем не остановишь .</text>
        <propbank>
          <rel relloc="8">стоит</rel>
          <arg type="ARGM-ADV" start="9" end="9">только</arg>
          <arg type="ARG1" start="10" end="10">начаться</arg>
        </propbank>
      </example>
      <example name="all it takes" src="Oksana Melnyk">
        <text>Стоить только сказать слово * улица * и моя собачка уже тут как тут .</text>
        <propbank>
          <rel relloc="0">Стоить</rel>
          <arg type="ARGM-ADV" start="?" end="?">только</arg>
          <arg type="ARG1" start="?" end="?">сказать слово *улица*</arg>
        </propbank>
      </example>
    </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/заявить-announce.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="заявить">
  <note>NOTES: Added for LORELEI to support aligning RU and EN texts. Data from Skatje Myers unless otherwise noted.</note>
    <roleset id="заявить.01" name="say, declare, announce">
      <aliases>
		<alias framenet="" pos="j" verbnet="">заявлять</alias>
		<alias framenet="" pos="j" verbnet="">заявляться</alias>
	  </aliases>
	  <note>Corresponds to FrameBank senses 1,6,7</note>
      <note>заявить.01 NOTES: Based on declare.01.</note>
      <roles>
	    <role descr="announcer" f="PAG" n="0">
        </role>
        <role descr="utterance" f="PPT" n="1">
        </role>
		<role descr="hearer" f="GOL" n="2">
        </role>
		<role descr="attributive" f="PRD" n="3">
        </role>
	  </roles>
      <example name="" src="А. И. Куприн, «Поединок», 1905 г. (цитата из Национального корпуса русского языка, см. Список литературы)" type="">
        <text>В таком случае заявляю, что ни на один из вопросов капитана Петерсона я отвечать не буду, — сказал Ромашов.</text>
        <arg f="" n="0">Ромашов</arg>
		<rel f="">заявляю</rel>
        <arg f="" n="1">что ни на один из вопросов капитана Петерсона я отвечать не буду</arg>
      </example>
	  <example name="" src="" type="">
        <text>На днях явился в кабинет отца старший сын и заявил ему, что он желает выйти из-под его опеки и самостоятельно вступить в свет.</text>
        <rel f="">заявил</rel>
		<arg f="" n="0">старший сын</arg>
		<arg f="" n="2">ему</arg>
        <arg f="" n="1">что он желает выйти из-под его опеки и самостоятельно вступить в свет</arg>
      </example>
	  <example name="" src="http://marker.framebank.ru/verbs_ex.php?lex=заявлять&cxid=3770" type="">
        <text>Начавший кампанию по выборам мэра Олег Сысуев заявляет об оказываемом на него давлении со стороны администрации области.</text>
        <arg f="" n="0">Олег Сысуев</arg>
		<rel f="">заявляет</rel>
        <arg f="" n="1">об оказываемом на него давлении со стороны администрации области</arg>
      </example>
	  <example name="" src="http://marker.framebank.ru/verbs_ex.php?lex=заявлять&cxid=14033" type="">
        <text>вот тогда он и заявляет: люблю, дескать, но не женюсь,</text>
        <arg f="" n="0">он</arg>
		<arg f="TMP" n="m">вот тогда</arg>
		<rel f="">заявляет</rel>
        <arg f="" n="1">люблю, дескать, но не женюсь</arg>
      </example>
	  <example name="" src="http://marker.framebank.ru/verbs_ex.php?lex=заявлять&cxid=16667" type="">
        <text>ребенок заявит (скорее всего плачем), что устал</text>
		<rel f="">заявит</rel>
        <arg f="" n="0">ребенок</arg>
		<arg f="" n="1">что устал</arg>
		<arg f="MNR" n="m">скорее всего плачем</arg>
	</roleset>
	
	<roleset id="заявить.02" name="accuse, tattle">
      <aliases>
		<alias framenet="" pos="j" verbnet="">заявлять</alias>
		<alias framenet="" pos="j" verbnet="">заявиться</alias>
		<alias framenet="" pos="v" verbnet="">заявляться</alias>
	  </aliases>
	  <note>Corresponds to FrameBank senses 2,3,4,5</note>
      <note>заявить.02 NOTES: Based on register.02.</note>
      <roles>
	    <role descr="entity registering" f="PAG" n="0">
        </role>
        <role descr="thing registered" f="PPT" n="1">
        </role>
		<role descr="registered with or for" f="GOL" n="2"/>
		<role descr="secondary predication" f="PRD" n="3"/>
	  </roles>
      <example name="" src="" type="http://marker.framebank.ru/verbs_ex.php?lex=заявлять&cxid=14184">
        <text>Но если его приходилось заявлять на матч , то об этом ему полагалось объявлять буквально за минуту до начала -- в противном случае он просто «рассыпался»</text>
		<arg f="" n="1">его</arg>
		<arg f="" n="3">на матч</arg>
		<rel f="">заявлять</rel>
      </example>
	     <example name="" src="" type="http://marker.framebank.ru/verbs_ex.php?lex=заявлять&cxid=16588">
        <text>Он заявил в милицию о краже.</text>
		<arg f="" n="0">Он</arg>
		<arg f="" n="1">о краже</arg>
		<arg f="" n="2">в милицию</arg>
		<rel f="">заявил</rel>
      </example>
	  	     <example name="" src="" type="http://marker.framebank.ru/verbs_ex.php?lex=заявлять">
        <text>Он боится, что на него заявят</text>
		<arg f="" n="0">Он</arg>
		<arg f="" n="1">на него</arg>
		<rel f="">заявят</rel>
      </example>
	  	     <example name="" src="" type="http://marker.framebank.ru/verbs_ex.php?lex=заявлять&cxid=14182">
        <text>Ассоциация впервые заявила о себе в 1992 году.</text>
		<arg f="" n="0">Ассоциация</arg>
		<arg f="" n="1">о себе</arg>
		<rel f="">заявила</rel>
      </example>
	  	     <example name="" src="" type="http://marker.framebank.ru/verbs_ex.php?lex=заявлять&cxid=16671">
        <text>Цель заявили громко -- «перспективы развития страны».</text>
		<arg f="" n="1">Цель</arg>
		<arg f="" n="1-APPOS">«перспективы развития страны»</arg>
		<arg f="MNR" n="m">громко</arg>
		<rel f="">заявили</rel>
      </example>
	  
	</roleset>
	
	<roleset id="заявить.03" name="appear, arrive suddenly and unexpectedly">
      <aliases>
		<alias framenet="" pos="j" verbnet="">заявляться</alias>
	  </aliases>
	  <note>Corresponds to FrameBank senses </note>
      <note>заявить.03 NOTES: Based on show_up.02.</note>
      <roles>
	    <role descr="thing appearing, showing up" f="PPT" n="1">
        </role>
        </role>
	  </roles>
      <example name="" src="" type="">
        <text>Заявился в гости в 3 ч. ночи.</text>
		<rel f="">Заявился</rel>
        <arg f="TMP" n="m">в 3 ч. ночи</arg>
      </example>
	</roleset>
