=== cu-clear/RussianPropbank/Frames/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>
<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>
<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*

  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
<!ELEMENT roleset (aliases?, note*, mappings*, note*, roles, ( example | note )*)>
<!ATTLIST roleset
  id   CDATA #REQUIRED
  name CDATA #REQUIRED
  usage CDATA #IMPLIED>
<!ELEMENT aliases (alias*, mwe*)>
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
pos (v | n | j | l | m | x | p) #REQUIRED
verbnet CDATA #REQUIRED
framenet CDATA #REQUIRED
usage CDATA #IMPLIED>
<!ELEMENT mwe (token*)>
<!ATTLIST mwe id CDATA #REQUIRED>
<!ELEMENT token (#PCDATA)>
<!ATTLIST token
slot (A | B | C | D | E | F | G | H | I | J | K | L | M) #REQUIRED
head CDATA #IMPLIED
dep CDATA #IMPLIED
pos CDATA #IMPLIED
arg CDATA #IMPLIED>


<!ELEMENT mappings (source, target)>
<!ATTLIST mappings alias CDATA #REQUIRED>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT roles   (note | role)*>
<!ELEMENT role (vnrole | fnrole)* >
<!--
  roles have a number (or an "M" associated
  with them, for common adjuncts that don't qualify for number argument status). 
  Both numbered arguments and adjuncts are labeled with the function tags from the list below:

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose
    PNC  purpose no cause (no longer used)
    CAU  cause
    CXN  constructional pattern (adjectival comparative marker)
    ADJ  adjectival (nouns only)
    COM  comitative
    DIS  discourse
    DSP  direct speech
    GOL  goal
    PAG  prototypical agent (function tag for arg1)
    PPT  prototypical patient (function tag for arg1)
    RCL  relative clause (no longer used)
    SLC  selectional constraint link
    VSP  verb specific (function tag for numbered arguments)
    LVB  light verb (for nouns only)

-->
<!ATTLIST role
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | m | M ) #REQUIRED
  f ( PAG | PPT | GOL | CXN | VSP | COM | ADJ | CAU | PRP | MNR | EXT | LOC | DIR | ADV | TMP | adv | tmp | pag | ppt | gol | vsp | com | adj | cau | prp | rec | mnr | ext | loc | dir | prd | PRD ) #REQUIRED
  descr CDATA #REQUIRED>
<!ELEMENT vnrole EMPTY>
<!ATTLIST vnrole
  vncls CDATA #REQUIRED
  vntheta (actor| Actor| actor1| Actor1 |actor2|  Actor2| agent| Agent|
  asset| Asset| attribute| Attribute| beneficiary| Beneficiary| cause| Cause|
  causer| Causer| co-agent | Co-Agent | co-patient | Co-Patient | co-theme | Co-Theme | 
  destination| Destination| experiencer| Experiencer| extent| Extent| 
  goal | Goal | initial_location | Initial_Location |
  instrument| Instrument| location| Location| material| Material| patient|
  Patient| patient1| Patient1| patient2| Patient2| pivot | Pivot | 
  predicate| Predicate| product| Product| recipient| Recipient| reflexive | Reflexive | result | Result |
  source| Source| stimulus| Stimulus| theme| Theme|theme1| Theme1| theme2| Theme2| time| Time| topic|
  Topic| Trajectory | trajectory | proposition| Proposition| value| Value | unspecified) #REQUIRED>
<!ELEMENT fnrole EMPTY>
<!ATTLIST fnrole
frame CDATA #REQUIRED
fe CDATA #REQUIRED>
<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->
<!ELEMENT example (inflection?, note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  type CDATA #IMPLIED
  src  CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>
<!ELEMENT inflection EMPTY>
<!ATTLIST inflection
  person (third | other | ns) "ns"
  tense  (present | past | future | ns) "ns"
  aspect (perfect | progressive | both | ns) "ns"
  voice  (active | passive | ns) "ns"
  form   (infinitive | gerund | participle | full | ns) "ns">
<!-- the n and f attributes corresponds to those of the roles
     described above -->
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | m | M | a | A) #REQUIRED
  f CDATA #IMPLIED>
<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  f CDATA #IMPLIED>

=== cu-clear/RussianPropbank/Frames/заметить-notice.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="заметить">
    <note>NOTES: Added for LORELEI to support aligning RU and EN texts. Data from Skatje Myers unless otherwise noted.</note>
    <roleset id="заметить.01" name="note, notice, see, observe">
      <aliases>
        <alias pos="v">замечать</alias>
        <alias pos="v">замечаться</alias>
        <alias pos="v">заметиться</alias>
      </aliases>
      <note>заметить.01 NOTES: Roleset based on English verb frame notice.01</note>
      <note>Corresponds to FrameBank senses 1, 2, 3, 6</note>
      <roles>
        <role descr="noticer" f="PAG" n="0"/>
        <role descr="noticed" f="PPT" n="1"/>
      </roles>
      <example name="all args" src="Татьяна Труфанова, «Не/друг», 2016 г. (цитата из Национального корпуса русского языка, см. Список литературы)">
        <text>Славик дёрнулся , как от электроразряда . Заметила ли она ручку ? ! — Поехали , — сказала Катерина . Саврасов нервно сглотнул и тронулся с места .</text>
        <propbank>
          <arg type="ARG0" start="9" end="9">она</arg>
          <rel relloc="7">Заметила</rel>
          <arg type="ARG1" start="10" end="10">ручку</arg>
        </propbank>
      </example>
      <example name="reflexive as passive" src="Russian National Corpus[Александр Ослон. Мир теорий в эпоху «охвата» // «Отечественные записки», 2003]">
        <text>Это замечается не только у детей , которые невольно воспринимают всякое мнение , предложенное им , но также у людей величайшей рассудительности и ума ; и им бывает очень трудно следовать собственному разуму и собственным наклонностям вопреки мнениям их друзей и ежедневных собеседников "</text>
        <propbank>
          <arg type="ARG1" start="0" end="0">Это</arg>
          <rel relloc="1">замечается</rel>
        </propbank>
      </example>
    </roleset>
    <roleset id="заметить.02" name="take note, remember, note, make note of">
      <aliases>
        <alias pos="v">замечать</alias>
      </aliases>
      <note>заметить.02 NOTES: Roleset based on English verb frame memorize.01</note>
      <note>Corresponds to FrameBank senses 5</note>
      <roles>
        <role descr="memorizer" f="PAG" n="0"/>
        <role descr="thing memorized" f="PPT" n="1"/>
      </roles>
      <example name="example" src="Russian National Corpus[Е. Л. Шварц. Сказка о потерянном времени (1940-1950)]">
        <text>Я вчера не заметил дороги обратно к домику ― боялся время потерять .</text>
        <propbank>
          <arg type="ARG0" start="0" end="0">Я</arg>
          <arg type="ARGM-TMP" start="1" end="1">вчера</arg>
          <arg type="ARGM-NEG" start="2" end="2">не</arg>
          <rel relloc="3">заметил</rel>
          <arg type="ARG1" start="4" end="7">дороги обратно к домику</arg>
        </propbank>
      </example>
    </roleset>
    <roleset id="заметить.03" name="remark, make note, say, mention">
      <aliases>
        <alias pos="v">замечать</alias>
      </aliases>
      <note>заметить.03 NOTES: Roleset based on English verb frame note.01</note>
      <note>Corresponds to FrameBank senses 4</note>
      <roles>
        <role descr="noter" f="PAG" n="0"/>
        <role descr="utterance" f="PPT" n="1"/>
        <role descr="hearer" f="GOL" n="2"/>
        <role descr="attribute of arg1" f="GOL" n="3"/>
      </roles>
      <example name="perfective" src="Russian National Corpus[Наталья Дубова. Вокруг ITSM // «Computerworld», 2004]">
        <text>" У нас уже есть примеры , когда при наличии определённой воли у бизнес - подразделений ИТ - департаменты начинают предоставлять и даже продавать именно услуги " , ― заметил он .</text>
        <propbank>
          <arg type="ARG1" start="1" end="25">У нас уже есть примеры , когда при наличии определённой воли у бизнес - подразделений ИТ - департаменты начинают предоставлять и даже продавать именно услуги</arg>
          <rel relloc="29">заметил</rel>
          <arg type="ARG0" start="30" end="30">он</arg>
        </propbank>
      </example>
    </roleset>
  </predicate>
  <predicate lemma="ни_в_чем_не_замечен">
    <roleset id="ни_в_чем_не_замечен.04" name="not suspected">
      <note>PASSIVE ONLY. NEGATIVE ONLY.</note>
      <aliases>
        <mwe id="ни_в_чем_не_замечен">
          <token slot="A" arg="" pos="" head="C" dep="">ни</token>
          <token slot="B" arg="" pos="" head="C" dep="">в</token>
          <token slot="C" arg="" pos="" head="A" dep="">чем</token>
          <token slot="D" arg="" pos="" head="A" dep="">не</token>
          <token slot="E" arg="" pos="" head="" dep="">замечен</token>
        </mwe>
      </aliases>
      <note>Based on English frame suspect.01</note>
      <roles>
        <role descr="suspecter" f="PAG" n="0"/>
        <role descr="suspicion: what arg0 thinks" f="PPT" n="1"/>
        <role descr="suspect; entity inspring suspicion in arg0" f="PRD" n="2"/>
      </roles>
      <example name="example" src="Russian National Corpus [М. А. Булгаков. Мастер и Маргарита, часть 2 (1929-1940)]">
        <text>Она дала самые лестные рекомендации коту , объяснила , что знает его пять лет с тех пор , как он был котёнком , ручается за него , как за самоё себя , доказала , что он ни в чём плохом не замечен и никогда не ездил в Москву .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">он</arg>
          <rel relloc="?">ни</rel>
          <rel relloc="?">в</rel>
          <rel relloc="?">чём</rel>
          <arg type="ARG1" start="39" end="39">плохом</arg>
          <rel relloc="?">не</rel>
          <rel relloc="?">замечен</rel>
        </propbank>
      </example>
    </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/следить-pay_attention.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="Следить">
    <roleset id="следить.01" name="Attend, watch, play close attention">
      <aliases>
        <alias pos="v">следить</alias>
        <alias pos="v">проследить</alias>
        <alias pos="j">следящий</alias>
        <alias pos="j">проследивший</alias>
	    </aliases>
	    <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
	    <note>NOTES: based on English attend.02</note>
      <roles>
        <role descr="Entity paying attention" f="PAG" n="0"/>
        <role descr="To what" f="PPT" n="1"/>
	    </roles>
      <example name="Arg0 and Arg1" src="_">
        <text>Мария следила за своей порцией .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">Мария</arg>
          <rel relloc="?">следила</rel>
	        <arg type="ARG1" start="?" end="?">за своей порцией</arg>
        </propbank>
      </example>
	  </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/платить-pay.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="Платить">
    <roleset id="платить.01" name="Pay">
      <aliases>
        <alias pos="v">платить</alias>
        <alias pos="v">заплатить</alias>
        <alias pos="v">оплатить</alias>
        <alias pos="v">оплачивать</alias>
        <alias pos="j">платящий</alias>
        <alias pos="j">заплативший</alias>
        <alias pos="j">оплаченный</alias>
        <alias pos="j">оплачивавший</alias>
	    </aliases>
	    <note>Corresponds to FrameBank senses [insert appropriate thing here, but also complain about the subtle difference on all the aliases that people refuse to elobarote on whne talking about the difference, focusing on grammatical difference vs sematinc differences.]</note>
	    <note>NOTES: based on English pay.01</note>
      <roles>
        <role descr="Payer or Buyer" f="PAG" n="0"/>
        <role descr="Money or form of payment" f="VSP" n="1"/>
        <role descr="Entity being paid" f="GOL" n="2"/>
        <role descr="Commodity, paid for what" f="ГОЛ" n="3"/>
	    </roles>
      <example name="Arg0, Arg1 and Arg3" src="RNC, Е. Ахматова [перевод романа Э. Булвер-Литтона с английского]. Кенелм Чиллингли, его приключения и взгляды на жизнь (1873)">
        <text>― Да, миссис Ботри платит за него восемь фунтов аренды, но доходов с лавки на это вполне хватает .</text>
        <propbank>
          <arg type="ARG0" start="2" end="3">миссис Ботри</arg>
          <rel relloc="4">платит</rel>
	        <arg type="ARG3" start="5" end="6">за него</arg>
          <arg type="ARG1" start="7" end="9">восемь фунтов аренды,</arg>
        </propbank>
      </example>
      <example name="Arg0 and Arg1 only" src="RNC, Нина Федорова. Семья [автоперевод] (1952)">
        <text>Я здесь заплачу 25 долларов ― и это все .</text>
        <propbank>
          <arg type="ARG0" start="0" end="0">Я</arg>
          <rel relloc="2">заплачу</rel>
	        <arg type="ARG1" start="3" end="4">25 долларов</arg>
        </propbank>
      </example>
        <example name="Arg0, Арг2, and Arg3" src="RNC, В. И. Максимов. Дневник научного сотрудника (2003)">
        <text>Так Ковалевский оплатил мне мой труд по написанию раздела в его НИР .</text>
        <propbank>
          <arg type="ARG0" start="1" end="1">Ковалевский</arg>
          <rel relloc="2">оплатил</rel>
	        <arg type="ARG2" start="3" end="3">мне</arg>
          <arg type="ARG3" start="4" end="5">мой труд</arg>
        </propbank>
        </example>
        <example name="Arg2 and Arg3 only" src="RNC, Н. Н. Никулин. Воспоминания о войне (1975)">
        <text>На войне те же дела оплачивались солдатскими жизнями .</text>
        <propbank>
          <arg type="ARG3" start="2" end="4">те же дела</arg>
          <rel relloc="5">оплачивались</rel>
	        <arg type="ARG1" start="6" end="7">солдатскими жизнями</arg>
        </propbank>
      </example>
	  </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/переполнить-overfill.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="переполнить">
    <note>NOTES: Added for LORELEI to support aligning RU and EN texts. Data from Skatje Myers.</note>
    <roleset id="переполнить.01" name="overfill">
      <aliases>
		<alias framenet="" pos="j" verbnet="">переполнен</alias>
		<alias framenet="" pos="j" verbnet="">переполненный</alias>
		<alias framenet="" pos="j" verbnet="">переполнивший</alias>
		<alias framenet="" pos="v" verbnet="">переполнять</alias>
		<alias framenet="" pos="j" verbnet="">переполняющий</alias>
		<alias framenet="" pos="j" verbnet="">переполнявший</alias>
		<alias framenet="" pos="j" verbnet="">переполняемый</alias>
		<alias framenet="" pos="v" verbnet="">переполниться</alias>
		<alias framenet="" pos="j" verbnet="">переполнившийся</alias>
		<alias framenet="" pos="v" verbnet="">переполняться</alias>
		<alias framenet="" pos="j" verbnet="">переполняющийся</alias>
		<alias framenet="" pos="j" verbnet="">переполнявшийся</alias>
      </aliases>
      <note>переполнить.01 NOTES: Roleset based on English verb frame fill.01</note>
      <roles>
        <role descr="agent, causer" f="PAG" n="0">
        </role>
        <role descr="container which has been filled beyond capacity" f="GOL" n="1">
        </role>
        <role descr="substance" f="PPT" n="2">
        </role>
      </roles>
      <example name="arg 0 and 1, inanimate causer" src="" type="">
        <text>Стекающая с речных водосборов вода переполнила русла основных рек .</text>
        <arg f="" n="0">Стекающая с речных водосборов вода</arg>
        <rel f="">переполнила</rel> 
        <arg f="" n="1">русла основных рек</arg>
      </example>
      <example name="passive participle, arg 1 and 2" src="" type="">
        <text>А тут случайно данный сайт , который как обычно переполнен скепсисом и негативом .</text>
		<arg f="" n="1">*PRO*</arg>
		<arg f="adv" n="m">как обычно</arg>
        <rel f="">переполнен</rel>
        <arg f="" n="2">скепсисом и негативом</arg>
      </example>
      <example name="active participle, arg 1 only" src="" type="">
        <text>Эвакуированные после урагана Катрина , переполнившие регион , усложняли эвакуацию во время урагана Рита , так же как и массовое бегство из Хьюстона окрестностей .</text>
        <arg f="" n="0">*PRO*</arg>
        <rel f="">переполнившие</rel>
        <arg f="" n="1">регион</arg>
      </example>
      <example name="adjective form" src="" type="">
        <text>Уезжающие на войну солдаты и офицеры в переполненных вагонах , как всходящие на крест , и равные , и вперемешку на ступеньках забитых вагонов ...</text>
        <rel f="">переполненных</rel>
        <arg f="com" n="m">вагонах</arg>
      </example>
      <example name="passive participle, args 1 and 2" src="web" type="">
        <text>Больницы переполнены ранеными .</text>
		<arg f="" n="1">Больницы</arg>
        <rel f="">переполнены</rel>
        <arg f="" n="2">ранеными</arg>
      </example>
      <example name="passive participle with auxiliary, arg 1 only" src="" type="">
        <text>Если в 2002 году оно было ПЕРЕПОЛНЕНО , то в 2011 чуть не ВЫСОХЛО полностью , что в т.ч. нарушив водоснабжение Новороссийска .</text>
        <arg f="adv" n="m">Если</arg>
		<arg f="tmp" n="m">в 2002 году</arg>
		<arg f="" n="1">оно</arg>
        <rel f="">ПЕРЕПОЛНЕНО</rel>
      </example>
	  <example name="reflexive perfective" src="https://dic.academic.ru/dic.nsf/ogegova/156546" type="">
        <text>Сердце переполнилось радостью</text>
		<arg f="" n="1">Сердце</arg>
        <rel f="">переполнилось</rel>
		<arg f="" n="2">радостью</arg>
      </example>
    </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/распределять-distribute.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="Распределять">
    <roleset id="распределять.01" name="Distribute, allot, apportion">
      <aliases>
        <alias pos="v">распределять</alias>
        <alias pos="v">распределить</alias>
        <alias pos="j">распределяющий</alias>
        <alias pos="j">распределённый</alias>
	    </aliases>
	    <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
	    <note>NOTES: based on English distribute.01</note>
      <roles>
        <role descr="Distributer" f="PAG" n="0"/>
        <role descr="thing distributed" f="PPT" n="1"/>
        <role descr="distributed to or among, benefactive" f="GOL" n="2"/>
	    </roles>
      <example name="Arg0 and Arg1" src="RNC, Т. В. Ершова, Ю. Е. Хохлов. Вперед к информационному обществу 2.0! // «Информационное общество», 2013">
        <text>А как вы распределяли обязанности ?</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">вы</arg>
          <rel relloc="?">распределяли</rel>
	        <arg type="ARG1" start="?" end="?">обязанности</arg>
        </propbank>
      </example>
      <example name="Arg0, Arg1, and Arg2" src="RNC, А. И. Минеев. Пять лет на острове Врангеля (1936)">
        <text>Я распределил свечи между сотрудниками так , чтобы по возможности удовлетворить всех на темные месяцы .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">Я</arg>
          <rel relloc="?">распределил</rel>
	        <arg type="ARG1" start="?" end="?">Sсвечиpan</arg>
	        <arg type="ARG2" start="?" end="?">между сотрудниками</arg>
        </propbank>
      </example>
	  </roleset>
    <roleset id="распределять.02" name="Allocate spacially, place, station">
      <aliases>
        <alias pos="v">распределять</alias>
        <alias pos="v">распределить</alias>
        <alias pos="j">распределяющий</alias>
        <alias pos="j">распределённый</alias>
	    </aliases>
	    <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
	    <note>NOTES: based on English spread_out.04</note>
      <roles>
        <role descr="Agent" f="PAG" n="0"/>
        <role descr="Thing placed" f="PPT" n="1"/>
        <role descr="Location" f="LOC" n="2"/>
	    </roles>
      <example name="Arg0, Arg1, and Arg2" src="RNC, Наталья Голованова. Под музыку сиреневых лун (2015)">
        <text>Вася распределил мусор по нескольким камням и вернулся на корабль .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">Вася</arg>
          <rel relloc="?">распределил</rel>
	        <arg type="ARG1" start="?" end="?">мусор</arg>
	        <arg type="ARG2" start="?" end="?">по нескольким камням</arg>
        </propbank>
      </example>
      <example name="Arg0, Arg1, and Arg2" src="RNC, Е. Л. Шварц. Дневник (1956)">
        <text>Она распределяла нас по комнатам , когда мы приехали , и , к моему негодованию , все путала меня с Брауном ― мы казались ей однофамильцами .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">Она</arg>
          <rel relloc="?">распределяла</rel>
	        <arg type="ARG1" start="?" end="?">нас</arg>
	        <arg type="ARG2" start="?" end="?">по комнатам</arg>
        </propbank>
      </example>
	  </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/уничтожать-destroy.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
    <predicate lemma="уничтожать">
        <roleset id="уничтожить.01" name="destroy">
            <aliases>
                <alias pos="v">уничтожать</alias>
                <alias pos="v">уничтожить</alias>
                <alias pos="j">уничтоженный</alias>
                <alias pos="j">уничтожающий</alias>
            </aliases>
            <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
            <note>NOTES: based on English destroy.01</note>
            <roles>
                <role descr="destroyer" f="PAG" n="0"/>
                <role descr="thing destroyed" f="PPT" n="1"/>
                <role descr="instrument of destruction" f="MNR" n="2"/>
            </roles>
            <lexlinks>
                <lexlink class="destroy.01" resource="English PropBank" version="3.4"/>
            </lexlinks>
            <example name="no instrument" src="Russian National Corpus">
                <text>Не случайно организатор теракта уничтожал свободный город-космополит , как будто боясь полюбить его .</text>
                <propbank>
                    <arg type="ARG0" start="2" end="3">организатор теракта</arg>
                    <rel relloc="4">уничтожал</rel>
                    <arg type="ARG1" start="5" end="6">свободный город-космополит</arg>
                </propbank>
            </example>
        </roleset>
    </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/молить-implore.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="Молить">
    <roleset id="молить.01" name="Implore, beg">
      <aliases>
        <alias pos="v">молить</alias>
        <alias pos="j">молящий</alias>
	    </aliases>
	    <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
	    <note>NOTES: based on English implore.01; there is no perfective counter part.</note>
      <roles>
        <role descr="Asker, agent" f="PAG" n="0"/>
        <role descr="Person being begged" f="PPT" n="1"/>
        <role descr="Thing asked for" f="PPT" n="2"/>
	    </roles>
      <example name="Arg0 and Arg1" src="RNC, С. В. Максимов. Сибирь и каторга (1871)">
        <text>Он меня молит , а я и слушать его не хочу , радуюсь .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">Он</arg>
	        <arg type="ARG1" start="?" end="?">меня</arg>
          <rel relloc="?">молит</rel>
        </propbank>
      </example>
      <example name="Arg0, Arg1, and Arg2" src="RNC, И. И. Лажечников. Последний Новик (1833)">
        <text>Все обитатели замка молили от души бога , чтоб он даровал будущей чете долгие лета .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">Все обитатели замка</arg>
          <rel relloc="?">молили</rel>
	        <arg type="ARG1" start="?" end="?">бога</arg>
	        <arg type="ARG2" start="?" end="?">чтоб он даровал будущей чете долгие лета</arg>
        </propbank>
      </example>
	  </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/разорять_ravage.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
    <predicate lemma="разорять">
        <roleset id="разорять.01" name="Ruin, ravage, be broke">
            <aliases>
                <alias pos="v">разорять</alias>
                <alias pos="v">разорить</alias>
                <alias pos="j">разоряющий</alias>
                <alias pos="j">разорённый</alias>
            </aliases>
            <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
            <note>NOTES: based on English broke.27</note>
            <roles>
                <role descr="Ruiner" f="PAG" n="0"/>
                <role descr="Person ruined or broke" f="PPT" n="1"/>
            </roles>
            <example name="Arg1 only" src="_">
                <text>Я разорён !</text>
                <propbank>
                    <arg type="ARG1" start="0" end="0">Я</arg>
                    <rel relloc="1">разорён</rel>
                </propbank>
            </example>
            <example name="Arg0 and Arg1" src="RNC, А. С. Суворин. Дневник (1893)">
                <text>Пьяный разоряет свою семью и т. д.</text>
                <propbank>
                    <arg type="ARG0" start="0" end="0">Пьяный</arg>
                    <rel relloc="1">разоряет</rel>
                    <arg type="ARG1" start="2" end="3">свою семью</arg>
                </propbank>
            </example>
        </roleset>
    </predicate>
</frameset>
