=== cu-clear/RussianPropbank/Frames/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>
<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>
<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*

  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
<!ELEMENT roleset (aliases?, note*, mappings*, note*, roles, ( example | note )*)>
<!ATTLIST roleset
  id   CDATA #REQUIRED
  name CDATA #REQUIRED
  usage CDATA #IMPLIED>
<!ELEMENT aliases (alias*, mwe*)>
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
pos (v | n | j | l | m | x | p) #REQUIRED
verbnet CDATA #REQUIRED
framenet CDATA #REQUIRED
usage CDATA #IMPLIED>
<!ELEMENT mwe (token*)>
<!ATTLIST mwe id CDATA #REQUIRED>
<!ELEMENT token (#PCDATA)>
<!ATTLIST token
slot (A | B | C | D | E | F | G | H | I | J | K | L | M) #REQUIRED
head CDATA #IMPLIED
dep CDATA #IMPLIED
pos CDATA #IMPLIED
arg CDATA #IMPLIED>


<!ELEMENT mappings (source, target)>
<!ATTLIST mappings alias CDATA #REQUIRED>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT roles   (note | role)*>
<!ELEMENT role (vnrole | fnrole)* >
<!--
  roles have a number (or an "M" associated
  with them, for common adjuncts that don't qualify for number argument status). 
  Both numbered arguments and adjuncts are labeled with the function tags from the list below:

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose
    PNC  purpose no cause (no longer used)
    CAU  cause
    CXN  constructional pattern (adjectival comparative marker)
    ADJ  adjectival (nouns only)
    COM  comitative
    DIS  discourse
    DSP  direct speech
    GOL  goal
    PAG  prototypical agent (function tag for arg1)
    PPT  prototypical patient (function tag for arg1)
    RCL  relative clause (no longer used)
    SLC  selectional constraint link
    VSP  verb specific (function tag for numbered arguments)
    LVB  light verb (for nouns only)

-->
<!ATTLIST role
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | m | M ) #REQUIRED
  f ( PAG | PPT | GOL | CXN | VSP | COM | ADJ | CAU | PRP | MNR | EXT | LOC | DIR | ADV | TMP | adv | tmp | pag | ppt | gol | vsp | com | adj | cau | prp | rec | mnr | ext | loc | dir | prd | PRD ) #REQUIRED
  descr CDATA #REQUIRED>
<!ELEMENT vnrole EMPTY>
<!ATTLIST vnrole
  vncls CDATA #REQUIRED
  vntheta (actor| Actor| actor1| Actor1 |actor2|  Actor2| agent| Agent|
  asset| Asset| attribute| Attribute| beneficiary| Beneficiary| cause| Cause|
  causer| Causer| co-agent | Co-Agent | co-patient | Co-Patient | co-theme | Co-Theme | 
  destination| Destination| experiencer| Experiencer| extent| Extent| 
  goal | Goal | initial_location | Initial_Location |
  instrument| Instrument| location| Location| material| Material| patient|
  Patient| patient1| Patient1| patient2| Patient2| pivot | Pivot | 
  predicate| Predicate| product| Product| recipient| Recipient| reflexive | Reflexive | result | Result |
  source| Source| stimulus| Stimulus| theme| Theme|theme1| Theme1| theme2| Theme2| time| Time| topic|
  Topic| Trajectory | trajectory | proposition| Proposition| value| Value | unspecified) #REQUIRED>
<!ELEMENT fnrole EMPTY>
<!ATTLIST fnrole
frame CDATA #REQUIRED
fe CDATA #REQUIRED>
<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->
<!ELEMENT example (inflection?, note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  type CDATA #IMPLIED
  src  CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>
<!ELEMENT inflection EMPTY>
<!ATTLIST inflection
  person (third | other | ns) "ns"
  tense  (present | past | future | ns) "ns"
  aspect (perfect | progressive | both | ns) "ns"
  voice  (active | passive | ns) "ns"
  form   (infinitive | gerund | participle | full | ns) "ns">
<!-- the n and f attributes corresponds to those of the roles
     described above -->
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | m | M | a | A) #REQUIRED
  f CDATA #IMPLIED>
<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  f CDATA #IMPLIED>

=== cu-clear/RussianPropbank/Frames/готовить-prepare_cook.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
    <predicate lemma="готовить">
        <roleset id="готовить.01" name="Prepare, make">
            <aliases>
                <alias pos="v">готовить</alias>
                <alias pos="v">приготовить</alias>
                <alias pos="j">готовящий</alias>
                <alias pos="j">приготовленный</alias>
            </aliases>
            <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
            <note>NOTES: based on English prepare.02</note>
            <roles>
                <role descr="Preparer, Agent" f="PAG" n="0"/>
                <role descr="Thing made ready" f="PPT" n="1"/>
                <role descr="Ready for, purpose or person" f="PRP" n="2"/>
            </roles>
            <example name="Arg0 and Arg1" src="RNC, Д. С. Данин. Нильс Бор (1969-1975)">
                <text>Он готовил тогда статью о связи между электрическими свойствами и поверхностным натяжением ртути
                    .
                </text>
                <propbank>
                    <arg type="ARG0" start="0" end="0">Он</arg>
                    <rel relloc="1">готовил</rel>
                    <arg type="ARG1" start="3" end="12">статью о связи между электрическими свойствами и поверхностным
                        натяжением ртути
                    </arg>
                </propbank>
            </example>
            <example name="Arg0, Arg1, and Arg2" src="RNC, Г. Я. Бакланов. Жизнь, подаренная дважды (1999)">
                <text>И родина приготовила для них место : в лагерях .</text>
                <propbank>
                    <arg type="ARG0" start="1" end="1">родина</arg>
                    <rel relloc="2">приготовила</rel>
                    <arg type="ARG3" start="3" end="4">для них</arg>
                    <arg type="ARG2" start="5" end="5">место</arg>
                </propbank>
            </example>
        </roleset>
        <roleset id="готовить.02" name="Cook, prepare">
            <aliases>
                <alias pos="v">готовить</alias>
                <alias pos="v">приготовить</alias>
                <alias pos="j">готовящий</alias>
                <alias pos="j">приготовленный</alias>
            </aliases>
            <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
            <note>NOTES: based on English prepare.01</note>
            <roles>
                <role descr="Chef, Agent" f="PAG" n="0"/>
                <role descr="Dish, Creation" f="PPT" n="1"/>
                <role descr="Ingredients, created from" f="DIR" n="2"/>
                <role descr="Benefactive, eater" f="GOL" n="3"/>
            </roles>
            <example name="Arg0 and Arg1"
                     src="RNC, Е. В. Салиас-де-Турнемир (Евгения Тур). Воспоминания о войне 1877-1878 гг. (1880)">
                <text>Дуняша между тем готовила в той же комнате чай .</text>
                <propbank>
                    <arg type="ARG0" start="0" end="0">Дуняша</arg>
                    <rel relloc="3">готовила</rel>
                    <arg type="ARG1" start="8" end="8">чай</arg>
                </propbank>
            </example>
            <example name="Arg1 and Arg2" src="RNC, Аркадий Кощеев. Царство флоры // «Уральский следопыт», 1982">
                <text>Из высушенных почек можно зимой готовить душистый чай с ароматом и вкусом южного ананаса .</text>
                <propbank>
                    <arg type="ARG2" start="0" end="2">Из высушенных почек</arg>
                    <rel relloc="5">готовить</rel>
                    <arg type="ARG1" start="6" end="13">душистый чай с ароматом и вкусом южного ананаса</arg>
                </propbank>
            </example>
            <example name="Arg0, Arg1, and Arg3" src="RNC, Екатерина Завершнева. Высотка (2012)">
                <text>У вас тут на столе одни шурупы , а мне Илонка ужин приготовила .</text>
                <propbank>
                    <arg type="ARG3" start="9" end="9">мне</arg>
                    <arg type="ARG0" start="10" end="10">Илонка</arg>
                    <arg type="ARG1" start="11" end="11">ужин</arg>
                    <rel relloc="12">приготовила</rel>
                </propbank>
            </example>
        </roleset>
    </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/обращаться-turn_to.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="обращаться">
    <note>NOTES: Added for LORELEI to support aligning RU and EN texts. Data from Skatje Myers unless otherwise noted.</note>
    <roleset id="обращаться.01" name="circulate, orbit, turn around">
      <aliases>
	  </aliases>
      <note>обращаться.01 NOTES: Based on orbit.01.</note>
      <roles>
        <role descr="revolving entity" f="PAG" n="0">
        </role>
        <role descr="point orbited" f="PPT" n="1">
        </role>
      </roles>
      <example name="revolve around" src="Russian National Corpus [В. П. Катаев. Алмазный мой венец (1975-1977)]">
        <text>в хорошем романе ( хотя я и не признаю деление прозы на жанры ) герой должен быть неподвижен , а обращаться вокруг него должен весь физический мир , что и составит если не галактику , то , во всяком случае , солнечную систему художественного произведения .</text>
        <propbank>
          <rel relloc="20">обращаться</rel>
          <arg type="ARG1" start="21" end="22">вокруг него</arg>
        </propbank>
      </example>
      <example name="circulate" src="Russian National Corpus [Ф. М. Достоевский. Записки из Мертвого дома (1862)]">
        <text>И уставали - то мы наконец , и легко в то же время становилось ; щеки краснели , кровь обращалась быстрее .</text>
        <propbank>
          <arg type="ARG0" start="18" end="18">кровь</arg>
          <rel relloc="19">обращалась</rel>
          <arg type="ARGM-ADV" start="20" end="20">быстрее</arg>
        </propbank>
      </example>
    </roleset>
    <roleset id="обращаться.02" name="treat, act, behave, use, handle">
      <aliases>
	  </aliases>
      <note>обращаться.02 NOTES: Based on treat.01.</note>
      <note>Corresponds to FrameBank senses 9</note>
      <roles>
        <role descr="assumer of attribute" f="PAG" n="0">
        </role>
        <role descr="entity treated" f="PPT" n="1">
        </role>
        <role descr="attribute" f="PRD" n="2"/>
      </roles>
      <example name="treat" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>Мачеха обращалась с ребенком плохо .</text>
        <propbank>
          <arg type="ARG0" start="0" end="0">Мачеха</arg>
          <rel relloc="1">обращалась</rel>
          <arg type="ARG1" start="2" end="3">с ребенком</arg>
          <arg type="ARG2" start="4" end="4">плохо</arg>
        </propbank>
      </example>
      <example name="handle" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>Мой сын с юных лет умеет обращаться с ружьем .</text>
        <propbank>
          <rel relloc="6">обращаться</rel>
          <arg type="ARG1" start="7" end="8">с ружьем</arg>
        </propbank>
      </example>
    </roleset>
    <roleset id="обращаться.03" name="turn to, face, direct, address">
      <aliases>
        <alias pos="j">обратить</alias>
        <alias pos="j">обращаться</alias>
        <alias pos="j">обратиться</alias>
      </aliases>
      <note>Corresponds to FrameBank senses 1,2,3,4,5</note>
      <note>обращаться.03 NOTES: Based on turn.01</note>
      <roles>
        <role descr="turner " f="PAG" n="0">
        </role>
        <role descr="direction, destination" f="PPT" n="1">
        </role>
      </roles>
      <note>English ARGM-LOC = Russian Arg3-GOL</note>
      <example name="address as" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>Он обращается ко мне на « вы » , хотя я давно ему тыкаю .</text>
        <propbank>
          <arg type="ARG0" start="0" end="0">Он</arg>
          <rel relloc="1">обращается</rel>
          <arg type="ARG1" start="2" end="3">ко мне</arg>
          <arg type="ARGM-MNR" start="4" end="7">на « вы »</arg>
        </propbank>
      </example>
      <example name="address with" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>Профессор обратился к первокурсникам с приветственной речью .</text>
        <propbank>
          <arg type="ARG0" start="0" end="0">Профессор</arg>
          <rel relloc="1">обратился</rel>
          <arg type="ARG1" start="2" end="3">к первокурсникам</arg>
          <arg type="ARGM-MNR" start="4" end="6">с приветственной речью</arg>
        </propbank>
      </example>
      <example name="turned to" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>Вдруг он обратился ко мне : « Вы не могли бы ему помочь ? »</text>
        <propbank>
          <arg type="ARGM-DIS" start="0" end="0">Вдруг</arg>
          <arg type="ARG0" start="1" end="1">он</arg>
          <rel relloc="2">обратился</rel>
          <arg type="ARG2" start="3" end="4">ко мне</arg>
          <arg type="ARGM-MNR" start="6" end="14">« Вы не могли бы ему помочь ? »</arg>
        </propbank>
      </example>
      <example name="directed towards" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>Все взгляды обратились к ней .</text>
        <propbank>
          <arg type="ARG0" start="0" end="1">Все взгляды</arg>
          <rel relloc="2">обратились</rel>
          <arg type="ARG1" start="3" end="4">к ней</arg>
        </propbank>
      </example>
      <example name="imperfective" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>Исследователь обращается к изучению рукописей XV века .</text>
        <propbank>
          <arg type="ARG0" start="0" end="0">Исследователь</arg>
          <arg type="ARG1" start="2" end="6">к изучению рукописей XV века</arg>
          <rel relloc="1">обращается</rel>
        </propbank>
      </example>
      <example name="" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>обратить оружие против кого - л .</text>
        <propbank>
          <arg type="ARG2" start="2" end="5">против кого - л</arg>
          <arg type="ARG1" start="1" end="1">оружие</arg>
          <rel relloc="0">обратить</rel>
        </propbank>
      </example>
    </roleset>
    <roleset id="обращаться.04" name="turn into, transform, exchange, convert">
      <aliases>
        <alias pos="j">обратить</alias>
        <alias pos="j">обращаться</alias>
        <alias pos="j">обратиться</alias>
      </aliases>
      <note>Corresponds to FrameBank senses 6,7,8,10</note>
      <note>обращаться.03 NOTES: Based on convert.01</note>
      <roles>
        <role descr="causer of transformation" f="PAG" n="0"/>
        <role descr="thing changing " f="PPT" n="1"/>
        <role descr="end state" f="PRD" n="2"/>
        <role descr="start state" f="VSP" n="3"/>
      </roles>
      <example name="" src="http://marker.framebank.ru/verbs_cx.php?lex=обращать">
        <text>Идеология расизма обращает человека в зверя .</text>
        <propbank>
          <arg type="ARG0" start="0" end="1">Идеология расизма</arg>
          <arg type="ARG2" start="4" end="5">в зверя</arg>
          <arg type="ARG3" start="3" end="3">человека</arg>
          <rel relloc="2">обращает</rel>
        </propbank>
      </example>
      <example name="" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>Вода обратилась в лед .</text>
        <propbank>
          <arg type="ARG3" start="0" end="0">Вода</arg>
          <arg type="ARG2" start="3" end="3">лед</arg>
          <rel relloc="1">обратилась</rel>
        </propbank>
      </example>
      <example name="" src="http://marker.framebank.ru/verbs_cx.php?lex=обращаться">
        <text>Деньги омертвевают , если они не обращаются .</text>
        <propbank>
          <arg type="ARG2" start="1" end="1">омертвевают</arg>
          <arg type="ARG3" start="0" end="0">Деньги</arg>
          <rel relloc="6">обращаются</rel>
        </propbank>
      </example>
      <example name="" src="http://marker.framebank.ru/verbs_cx.php?lex=обращать">
        <text>Туземцев обратили в христианство</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">Все</arg>
          <arg type="ARG3" start="0" end="0">Туземцев</arg>
          <arg type="ARG2" start="3" end="3">христианство</arg>
          <rel relloc="1">обратили</rel>
        </propbank>
      </example>
    </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/ломать-break.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="Ломать">
    <roleset id="ломать.01" name="Break">
      <aliases>
        <alias pos="v">ломать</alias>
        <alias pos="v">сломать</alias>
        <alias pos="v">поломать</alias>
        <alias pos="j">ломающий</alias>
        <alias pos="j">сломанный</alias>
        <alias pos="j">поломанный</alias>
	    </aliases>
	    <note>Corresponds to FrameBank senses [insert appropriate thing here]</note>
	    <note>NOTES: based on English break.01</note>
      <roles>
        <role descr="Breaker" f="PAG" n="0"/>
        <role descr="Thing broken" f="PPT" n="1"/>
        <role descr="Instrument" f="MNR" n="2"/>
        <role descr="Pieces" f="PRD" n="3"/>
	    </roles>
      <example name="Arg0 and Arg1" src="_">
        <text>Мы сломали стол</text>
        <propbank>
          <arg tpye="ARG0" start="?" end="?">Мы</arg>
          <rel relloc="?">сломали</rel>
	        <arg tpye="ARG1" start="?" end="?">стол</arg>
        </propbank>
      </example>
      <example name="Arg0, Arg1, and Arg2" src="_">
        <text>Ты своим сарказмом ломаешь все свои шансы .</text>
        <propbank>
          <arg tpye="ARG0" start="?" end="?">Ты</arg>
          <arg tpye="ARG2" start="?" end="?">своим сарказмом</arg>
          <rel relloc="?">ломаешь</rel>
	        <arg tpye="ARG1" start="?" end="?">все свои шансы</arg>
        </propbank>
      </example>
      <example name="Arg0, Arg1, and Arg3" src="RNC, А. И. Куприн. Психея (1892)">
        <text>Минутами мне кажется , будто кто-то ломает мой череп на части , и каждое движение причиняет чудовищную боль .</text>
        <propbank>
          <arg tpye="ARG0" start="?" end="?">кто-то</arg>
          <rel relloc="?">ломает</rel>
          <arg tpye="ARG1" start="?" end="?">мой череп</arg>
	        <arg tpye="ARG3" start="?" end="?">на части</arg>
        </propbank>
      </example>
	  </roleset>
  </predicate>
</frameset>

=== cu-clear/RussianPropbank/Frames/обнаружить-discover.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
  <predicate lemma="обнаружить">
    <note>NOTES: Added for LORELEI to support aligning RU and EN texts. Data from Skatje Myers.</note>
    <roleset id="обнаружить.01" name="discover">
      <aliases>
        <alias pos="n">обнаружение</alias>
        <alias pos="j">обнаруживший</alias>
        <alias pos="j">обнаруженный</alias>
        <alias pos="j">обнаружен</alias>
        <alias pos="v">обнаруживать</alias>
        <alias pos="j">обнаруживающий</alias>
        <alias pos="j">обнаруживавший</alias>
        <alias pos="j">обнаруживаемый</alias>
        <alias pos="v">обнаруживаться</alias>
        <alias pos="j">обнаружившийся</alias>
        <alias pos="j">обнаруживающийся</alias>
        <alias pos="j">обнаруживавшийся</alias>
      </aliases>
      <note>Corresponds to FrameBank senses 1,2,3,4,8</note>
      <note>обнаружить.01 NOTES: Frame based on English discover.01</note>
      <roles>
        <role descr="finder" f="PAG" n="0">
				</role>
        <role descr="thing found, discovery" f="PPT" n="1">
				</role>
        <role descr="benefactive, found for" f="GOL" n="2"/>
        <role descr="attribute on arg1 (found out to be/as what)" f="PRD" n="3"/>
      </roles>
      <example name="clausal arg1 " src="">
        <text>да и потом повезло с камнем - мой 2 - ядерный фен оказался 4 - ядерным и когда посмотрел на рейтинги камней с удивлением обнаружил , что он конкуренит не Е - линейке , а Q с ее 4 ядрами и ценниками ... Был Очень приятно удивлен .</text>
        <propbank>
          <arg type="ARGM-ADV" start="22" end="23">с удивлением</arg>
          <rel relloc="24">обнаружил</rel>
          <arg type="ARG1" start="26" end="41">что он конкуренит не Е - линейке , а Q с ее 4 ядрами и ценниками</arg>
        </propbank>
      </example>
      <example name="found, perfective passive participle" src="">
        <text>Утром 20 декабря в дежурную часть Центрально - Городского райотдела милиции поступило сообщение о том , что в палате интенсивной терапии диспансера обнаружен труп пациента с признаками насильственной смерти .</text>
        <propbank>
          <arg type="ARGM-LOC" start="18" end="21">палате интенсивной терапии диспансера</arg>
          <rel relloc="22">обнаружен</rel>
          <arg type="ARG1" start="23" end="28">труп пациента с признаками насильственной смерти</arg>
        </propbank>
      </example>
      <example name="arg0 and arg1" src="">
        <text>– Уже утром , после того , как дебошир покинул больничные покои , медперсонал обнаружил второго пациента без признаков жизни с веревкой на шее .</text>
        <propbank>
          <arg type="ARG0" start="13" end="13">медперсонал</arg>
          <rel relloc="14">обнаружил</rel>
          <arg type="ARG1" start="15" end="23">второго пациента без признаков жизни с веревкой на шее</arg>
        </propbank>
      </example>
      <example name="understood arg1" src="">
        <text>Через год приезжаю в домик , узнаю , что умерла , соседи только через неделю обнаружили .</text>
        <propbank>
          <arg type="ARG0" start="11" end="11">соседи</arg>
          <arg type="ARGM-TMP" start="12" end="14">только через неделю</arg>
          <rel relloc="15">обнаружили</rel>
        </propbank>
      </example>
      <example name="found, aux. passive construction, arg1" src="">
        <text>Источники из Пентагона сообщают , что в результате предварительного осмотра было обнаружено , что , возможно , использовалось от 400 до 500 футов взрывчатого вещества .</text>
        <propbank>
          <arg type="ARGM-CAU" start="6" end="9">в результате предварительного осмотра</arg>
          <rel relloc="11">обнаружено</rel>
          <arg type="ARG1" start="13" end="24">что , возможно , использовалось от 400 до 500 футов взрывчатого вещества</arg>
        </propbank>
      </example>
      <example name="discovered, arg0 and arg1 inverse word order" src="">
        <text>Она не уточнила , какого рода деталь обнаружили таможенники , однако отметила , что " документального подтверждения о принадлежности обнаруженного блока к самолетам типа МиГ-23 и основания его вывоза не предоставлено " .</text>
        <propbank>
          <arg type="ARG1" start="4" end="6">какого рода деталь</arg>
          <rel relloc="7">обнаружили</rel>
          <arg type="ARG0" start="8" end="8">таможенники</arg>
        </propbank>
      </example>
      <example name="figured out, concluded" src="">
        <text>Access обнаружил , что моя база данных находится в несогласованном состоянии</text>
        <propbank>
          <arg type="ARG0" start="0" end="0">Access</arg>
          <rel relloc="1">обнаружил</rel>
          <arg type="ARG0" start="3" end="10">что моя база данных находится в несогласованном состоянии</arg>
        </propbank>
      </example>
      <example name="adverbial" src="">
        <text>В 2013 году планетоход Curiosity , принадлежащий NASA , продолжил делать исторические открытия на Марсе , обнаружив , что одно из высохших озер на красной планете могло быть хранителем жизни более 3 миллиардов лет назад .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">*PRO*</arg>
          <rel relloc="16">обнаружив</rel>
          <arg type="ARG1" start="18" end="34">что одно из высохших озер на красной планете могло быть хранителем жизни более 3 миллиардов лет назад</arg>
        </propbank>
      </example>
      <example name="reflexive" src="https://dic.academic.ru/dic.nsf/ogegova/132054">
        <text>Пропавшая книга обнаружилась .</text>
        <propbank>
          <arg type="ARG1" start="0" end="1">Пропавшая книга</arg>
          <rel relloc="2">обнаружилась</rel>
        </propbank>
      </example>
    </roleset>
    <roleset id="обнаружить.02" name="reveal">
      <aliases>
        <alias pos="n">обнаружение</alias>
        <alias pos="j">обнаруживший</alias>
        <alias pos="j">обнаруженный</alias>
        <alias pos="j">обнаружен</alias>
        <alias pos="v">обнаруживать</alias>
        <alias pos="j">обнаруживающий</alias>
        <alias pos="j">обнаруживавший</alias>
        <alias pos="j">обнаруживаемый</alias>
        <alias pos="v">обнаруживаться</alias>
        <alias pos="j">обнаружившийся</alias>
        <alias pos="j">обнаруживающийся</alias>
        <alias pos="j">обнаруживавшийся</alias>
      </aliases>
      <note>Corresponds to FrameBank senses 5,6,7 </note>
      <note>обнаружить.02 NOTES: based on English uncover.01</note>
      <roles>
        <role descr="discoverer" f="PAG" n="0">
				</role>
        <role descr="thing discovered" f="PPT" n="1">
				</role>
        <role descr="secondary attribute" f="PRD" n="2"/>
      </roles>
      <example name="make visible" src="Чехов">
        <text>Губы открылись и обнаружили стиснутые зубы .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">*Trace-1*</arg>
          <rel relloc="3">обнаружили</rel>
          <arg type="ARG0" start="4" end="5">стиснутые зубы</arg>
        </propbank>
      </example>
      <example name="make obvious" src="Чехов">
        <text>Считал неприличным … обнаружить свою радость .</text>
        <propbank>
          <arg type="ARG0" start="?" end="?">PRO</arg>
          <rel relloc="3">обнаружить</rel>
          <arg type="ARG1" start="4" end="5">свою радость</arg>
        </propbank>
      </example>
    </roleset>
  </predicate>
</frameset>
